CFLAGS=-Wall -Wextra -xc -g -std=gnu99

pratybos12: pratybos12.o helpers.o test_algorithm.o bubble_sort_a.o bubble_sort_b.o bubble_sort_a.o bubble_sort_b.o bubble_sort_c.o bubble_sort_d.o bubble_sort_e.o bubble_sort_f.o bubble_sort_b_and_c.o bubble_sort_b_and_e.o bubble_sort_b_and_f.o bubble_sort_c_and_e.o bubble_sort_c_and_f.o bubble_sort_e_and_f.o bubble_sort_b_and_e_and_f.o bubble_sort_b_and_c_and_e_and_f.o quicksort.o insertion_sort.o selection_sort.o top_down_merge_sort.o

clean:
	rm pratybos12
