CC=gcc
#CFLAGS=-DNDEBUG -fPIC -Wall -g -std=gnu11 #-Wextra -Wconversion -pedantic
CFLAGS=-fPIC -Wall -g -lm -std=gnu11 #-Wextra -Wconversion -pedantic

kontrolinis1: 
	$(CC) $(CFLAGS) kontrolinis1.c -o kontrolinis1

clean:
	rm kontrolinis1

rebuild: clean kontrolinis1
